<section class="logo_image">
    <img src="./assets/img/x_logo.jpg" width="10%" alt="Logotipo da X">
</section>
<section class="authenticate_container">
    <h1>Acontencedo agora</h1>
    <section class="authenticate">
        <a href="http://google.com" class="btn btn-light" target="_blank" rel="noopener noreferrer">Inscreva-se no google</a>
        <a href="http://apple.com" class="btn btn-light" target="_blank" rel="noopener noreferrer">Inscreva-se com Apple</a>
        <hr>
        <a class="btn btn-primary" href="/subscribe">Criar conta</a>
        <small>Ao se inscrever, você concorda com os <a href="">Termos de serviço</a> e a <a href="">Política de Privacidade</a>, incluindo o <a href="">Uso de Cookies</a>.</small>
        <div class="login">
            <h2>Já tem conta ?</h2>
            <a href="">Entrar</a>
        </div>
    </section>
</section>