<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./assets/img/x_logo.jpg" type="image/x-icon">
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css" media="all">
    <title>X. O que ta acontecendo / X</title>
</head>
<body>
    <?php $this->content(); ?>
</body>
</html>